server:
  port: 8070 #Puerto en el que funcionara este mcsv concreto

spring:
  application:
    name: microservice.timeLine #Nombre del mcsv, comprobar el POM
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/timeLineDb #Nombre de la BBDD
    username: root #Username
    password:      #Password

  jpa:
    hibernate:
      ddl-auto: create #Crea las tablas de forma automatica
    database: mysql
    database.platform: org.hibernate.dialect.MySQL8Dialect

  config:
    import: optional:configserver:http://localhost:8888

eureka:
  instance:
    hostname: localhost #Para que se registre de forma automatica
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka #Aqui esta funcionando eureka por defecto


