server:
  port: 8080 #Server por defecto

spring:
  config:
    import: optional:configserver:http://localhost:8888
  application:
    name: microservice-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: user
          uri: http://localhost:8090
          predicates:
            - Path=/app/user/**
        - id: timeline
          uri: http://localhost:8070
          predicates:
            - Path=/app/timeline/**
